name: Build Flutter APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: 

jobs:
  build:
    name: Build & Export APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create Fresh Project & Build
        run: |
          # ۱. ساخت پروژه جدید با شناسه اختصاصی
          flutter create --org com.erfan.tapsilink clean_tapsi_app
          
          # ۲. کپی کدهای شما
          cp lib/main.dart clean_tapsi_app/lib/main.dart
          cp pubspec.yaml clean_tapsi_app/pubspec.yaml
          if [ -f "icon.png" ]; then cp icon.png clean_tapsi_app/icon.png; fi
          
          cd clean_tapsi_app
          
          # ۳. 🪄 تزریق مجوز اینترنت و ارتقای minSdkVersion به 21 (نیاز قطعی وب‌ویو) 🪄
          sed -i '/<manifest/a \    <uses-permission android:name="android.permission.INTERNET"/>' android/app/src/main/AndroidManifest.xml
          sed -i 's/flutter.minSdkVersion/21/g' android/app/build.gradle
          
          # ۴. دانلود پکیج‌ها
          flutter pub get
          
          # ۵. تغییر اسم برنامه به Tapsi link
          flutter pub run rename_app:main all="Tapsi link"
          
          # ۶. ساخت اتوماتیک آیکون جدید
          if [ -f "icon.png" ]; then flutter pub run flutter_launcher_icons; fi
          
          # ۷. رفع باگ Proguard
          find ~/.pub-cache/hosted/pub.dev/ -type f -name "build.gradle" -exec sed -i 's/proguard-android.txt/proguard-android-optimize.txt/g' {} +
          
          # ۸. بیلد نهایی
          flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Tapsi-Client-Release
          path: clean_tapsi_app/build/app/outputs/flutter-apk/app-release.apk
